apiVersion: v1
kind: Secret
metadata:
  name: task-app-secrets
  namespace: task-app
type: Opaque
stringData:
  POSTGRES_DB: taskdb
  POSTGRES_USER: taskuser
  POSTGRES_PASSWORD: taskpass
  POSTGRES_HOST: task-postgres
  POSTGRES_PORT: "5432"
  BACKEND_PORT: "3000"
  API_URL: http://task-backend:3000
