apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-backend
  template:
    metadata:
      labels:
        app: task-backend
    spec:
      containers:
        - name: task-backend
          image: sen5e1/task-backend:1.0
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: task-postgres
            - name: DB_NAME
              value: taskdb
            - name: DB_USER
              value: taskuser
            - name: DB_PASSWORD
              value: taskpass
            - name: DB_PORT
              value: "5432"
            - name: PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: task-backend
spec:
  selector:
    app: task-backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP