apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-backend
  namespace: task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-app
      component: backend
  template:
    metadata:
      labels:
        app: task-app
        component: backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: task-backend
          image: sen5e1/task-backend:1.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: task-app-secrets
