apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-frontend
  namespace: task-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-frontend
  template:
    metadata:
      labels:
        app: task-frontend
    spec:
      containers:
        - name: task-frontend
          image: sen5e1/task-frontend:1.0
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: task-app-secrets
                  key: API_URL
