apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: task-postgres
  namespace: task-app
spec:
  serviceName: task-postgres
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: task-app
      component: database
  template:
    metadata:
      labels:
        app: task-app
        component: database
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: task-postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: task-app-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: task-app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-app-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              readOnly: true
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init-sql
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
