apiVersion: v1
kind: Service
metadata:
  name: task-postgres
  namespace: task-app
spec:
  selector:
    app: task-app
    component: database
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
